enableGlobalCache: true

packageExtensions:
  "@sapphire/decorators@^6.0.0":
    dependencies:
      "@sapphire/discord.js-utilities": "^6.0.1"
      "@sapphire/framework": "^4.0.1"
      discord.js: ^14.7.1
  "@sapphire/discord.js-utilities@^6.0.1":
    dependencies:
      discord-api-types: "*"
      discord.js: ^14.7.1
  "@sapphire/framework@^4.0.1":
    dependencies:
      "@discordjs/builders": "*"
      "@sapphire/discord.js-utilities": "^6.0.1"
      discord.js: ^14.7.1

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
